---
- hosts: all
  become: yes
  become_user: root
  tasks:
       - name: Run the equivalent of "apt-get update" as a separate step
         apt:
           upgrade: yes
           update_cache: yes
         when:
           - ansible_os_family == "Debian"
           - ansible_distribution == "Ubuntu"
